version: '3.7'

services:
  db:
    image: postgres:14
    networks:
      - app_net
    environment:
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
    restart: always

  app:
    image: nestjs-app
    ports:
      - 3000:3000
    networks:
      - app_net
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

networks:
  app_net: