version: '3.7'

services:

  db:
    image: postgres:14
    environment:
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=nestjs
      - POSTGRES_PASSWORD=nestjs

  app:
    image: nestjs-app
    ports:
      - 3000:3000
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_DB=nestjs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Santi_018